// Central help texts for product fields — the ⓘ tooltip next to each label.
// Keyed by the attribute key (AttrField) or column key (EditableField); a
// field with no entry simply shows no icon. Explicit `help` props override.

export const FIELD_HELP = {
  // ---------- Identification ----------
  upc: 'Universal Product Code — the 12-digit barcode. Unique per product; never shared between variants.',
  manufacturer: 'Company that manufactures the product (may differ from the brand).',
  brand: 'Brand shown to shoppers on every marketplace.',
  category: 'Product category — drives which spec fields, templates and export rules apply.',
  series: 'Product line / collection name (e.g. Versa, Pietra).',
  family_number: 'Internal number grouping variants of the same model (finishes, gauges…). Videos and documents are shared across the family.',
  product_type: 'Finer-grained type inside the category, used by some marketplace templates.',
  hs_code: 'Harmonized System customs code used for international shipping and duties.',
  country_of_origin: 'Country of manufacture — required by customs and most marketplaces.',
  product_url: 'Public product page on the SinksDirect website.',

  // ---------- Content ----------
  description: 'Main sales description (rich text). Pushed to Wix and used as a base for marketplace copy.',
  description_fr: 'French sales description, used by Canadian bilingual channels.',
  general_title_en: 'English listing title used by marketplace templates.',
  general_title_fr: 'French listing title for Canadian bilingual channels.',
  marketing_copy: 'Short marketing blurb for templates that want a one-liner instead of the full description.',
  bullet_points_fr: 'French feature bullets, one per line — mirror of the English bullets.',
  keywords_en: 'English search keywords (comma-separated) — feed Amazon Generic Keywords and site search.',
  keywords_fr: 'French search keywords for bilingual channels.',
  quickbooks_description: 'Internal short description used in QuickBooks — not shown to shoppers.',
  notes: 'Internal notes for the team — never exported anywhere.',
  standards_compliance: 'Free-text summary of standards this product meets, shown on some templates.',

  // ---------- Physical / dimensions ----------
  external_dimensions_in: 'Outside dimensions of the product (length × width × depth), in inches.',
  internal_dimensions_in: 'Inside bowl dimensions (length × width × depth), in inches.',
  cut_out_dimensions_in: 'Countertop cut-out size required for installation, in inches.',
  shipping_dimensions_in: 'Boxed dimensions used for freight quotes and marketplace logistics fields.',
  product_weight_lb: 'Product weight without packaging, in pounds.',
  shipping_weight_lb: 'Boxed shipping weight in pounds — what carriers and marketplaces bill by.',
  min_external_cabinet_size_in: 'Smallest cabinet width the sink fits into, measured outside, in inches.',
  min_internal_cabinet_size_in: 'Smallest interior cabinet width required, in inches.',
  max_deck_thickness_in: 'Thickest countertop/deck the fixture can clamp onto, in inches.',
  drain_diameter_in: 'Drain opening diameter in inches (standard kitchen drain is 3.5").',
  sink_radius_mm: 'Interior corner radius in millimetres — smaller radius = squarer corners.',
  gauge: 'Steel thickness — LOWER gauge means THICKER steel (16G is thicker than 18G).',
  install_hole_diameter_in: 'Diameter of the faucet installation hole, in inches.',
  install_hole_diameter_mm: 'Diameter of the faucet installation hole, in millimetres.',
  overall_shape: 'Overall product silhouette (rectangular, round, D-shape…).',
  sink_shape: 'Bowl shape as shoppers filter by it (rectangular, round, farmhouse…).',
  pattern: 'Decorative pattern, if any.',

  // ---------- Material / construction ----------
  material: 'Primary material — dropdown lists the values already used in the catalog.',
  finish: 'Surface finish/color as marketed (e.g. Brushed Stainless Steel).',
  craftsmanship: 'Construction technique highlight (e.g. handmade, precision-formed).',
  wood_species: 'Wood type for bamboo/wood accessories.',
  antimicrobial: 'Whether the surface has an antimicrobial treatment.',
  lead_free: 'Meets low-lead requirements for drinking-water contact.',
  bpa_free: 'Material contains no bisphenol-A.',

  // ---------- Sink configuration ----------
  number_of_bowls: 'How many bowls the sink has.',
  bowl_configuration: 'Bowl layout (single, 50/50 double, 60/40…).',
  basin_split: 'How the basin divider splits the bowls.',
  low_divider: 'Divider lower than the rim, letting large cookware span both bowls.',
  installation_type: 'How the sink installs: undermount, drop-in (topmount), dual-mount, farmhouse…',
  drain_hole_location: 'Where the drain sits in the bowl (center, rear, offset).',
  drain_overflow: 'Whether the sink has an overflow drain.',
  overflow: 'Whether the fixture includes an overflow.',
  faucet_centers: 'Distance between outer faucet holes, in inches (e.g. 4" centerset, 8" widespread).',
  faucet_hole_center_spacing: 'Spacing between pre-drilled faucet holes, in inches.',
  number_of_faucet_holes: 'Pre-drilled faucet holes on the sink deck.',
  includes_grids: 'Whether bottom grids ship in the box.',
  grids_model_code: 'SKU of the compatible/included bottom grid.',
  strainer_model: 'SKU of the compatible/included strainer.',
  compatible_drain_assembly: 'Drain assembly SKU(s) that fit this product.',
  compatible_faucet_type: 'Faucet styles that pair with this sink.',
  compatible_deck_plate: 'Deck plate SKU(s) that fit this faucet.',
  compatible_pedestal: 'Pedestal SKU(s) that fit this bathroom sink.',
  pedestal_included: 'Whether the pedestal ships in the box.',
  console_included: 'Whether the console/stand ships in the box.',
  accessories_included: 'Accessories that ship in the box (grid, strainer, colander…).',
  has_grooves: 'Whether the board/surface has grooves.',

  // ---------- Faucet configuration ----------
  spout_type: 'Spout style (gooseneck/high-arc, pull-down…). Dropdown lists values already in the catalog.',
  swivel_spout: 'Whether the spout rotates.',
  spout_rotation_degrees: 'How far the spout swivels, in degrees (e.g. 360).',
  max_flow_rate: 'Maximum water flow in gallons per minute, typically measured at 60 psi.',
  number_of_installation_holes: 'Holes required in the counter/sink to install this faucet.',
  mounting_type: 'How the faucet mounts (deck-mount, wall-mount…).',
  connection_size: 'Water supply connection diameter in inches — enter the decimal (0.375 = 3/8").',
  lock_type: 'How the spray head docks back (magnetic, click-lock…).',
  hot_cold_dispenser: 'Whether it dispenses both hot and cold water.',
  faucet_height_in: 'Total faucet height from the deck, in inches.',
  spout_height_in: 'Height from the deck to the spout outlet, in inches.',
  spout_reach_in: 'Horizontal distance from the mounting hole to the water stream, in inches.',
  number_of_handles: 'Handles controlling the water (1 = single-handle mixer).',
  handle_style: 'Handle design (lever, cross, knob…).',
  handle_material: 'Material of the handle(s).',
  cold_start_handle: 'Handle starts in the cold position, saving energy on quick uses.',
  cartridge_type: 'Internal valve cartridge technology (usually ceramic disc).',
  cartridge_size: 'Cartridge diameter (e.g. 35 mm) — needed for replacements.',
  spray_type: 'Spray head type (pull-down, pull-out, side spray…).',
  spray_head_functions: 'Modes on the spray head (stream, spray, pause…).',
  spray_function_activation: 'How spray modes switch (button, toggle…).',
  spray_included: 'Whether a side spray ships in the box.',
  laminar_flow: 'Produces a clear, non-aerated water stream.',
  aerator_included: 'Whether an aerator ships installed or in the box.',
  hose_included: 'Whether the supply/spray hose ships in the box.',
  pull_down_hose_model: 'Replacement SKU of the pull-down hose.',
  supply_line_included: 'Whether water supply lines ship in the box.',
  valve_included: 'Whether the rough-in valve ships in the box.',
  deck_plate_included: 'Whether the deck plate (escutcheon) ships in the box.',
  application: 'Intended use/location for this product (kitchen, bar, laundry…).',

  // ---------- Accessories ----------
  flexible_cutting_board: 'Board flexes to funnel chopped food.',
  juice_grooves: 'Perimeter groove that catches liquids while cutting.',
  reversible: 'Both sides are usable.',
  over_the_sink: 'Designed to sit across the sink rim.',
  knife_included: 'Whether a knife ships with the board.',
  handles_included: 'Whether carrying handles are built in.',
  number_of_pieces: 'Pieces included in the set.',

  // ---------- Care / warranty ----------
  product_care: 'Care & cleaning instructions shown on listings — standardized per material.',
  durability_tags: 'Durability highlights (scratch-resistant, heat-resistant…) used by templates.',
  warranty: 'Warranty summary text shown to shoppers.',
  warranty_length: 'Warranty duration (Lifetime, 1 Year…).',
  commercial_warranty: 'Warranty terms when used commercially (often shorter than residential).',

  // ---------- Certifications & compliance ----------
  cupc_certified: 'Certified by IAPMO to the Uniform Plumbing Code for the US and Canada.',
  upc_certified: 'Certified to the Uniform Plumbing Code (IAPMO).',
  ada_compliant: 'Meets Americans with Disabilities Act accessibility requirements.',
  doe_compliant: 'Meets the U.S. Department of Energy water-conservation standards.',
  asse_1001_certified: 'Backflow-prevention (anti-siphon) performance standard.',
  asme_csa_certified: 'ASME A112.18.1/CSA B125.1 — North American standard for plumbing supply fittings.',
  asme_a112_19_1_compliant: 'Standard for enameled cast-iron and steel plumbing fixtures.',
  asme_a112_19_2_compliant: 'Standard for ceramic plumbing fixtures.',
  asme_a112_19_3_compliant: 'Standard for stainless steel plumbing fixtures.',
  asme_a112_19_4_compliant: 'Standard for porcelain-enameled formed steel fixtures.',
  ansi_z124_6_97_compliant: 'Standard for plastic sinks.',
  csa_b45_5_iapmo_z124_compliant: 'Standard for plastic/composite plumbing fixtures.',
  ww_p_541_certified: 'US federal specification for plumbing fixtures.',
  nsf_certified: 'NSF/ANSI certified for food-zone or drinking-water safety.',
  nsf_ansi_61_certified: 'NSF/ANSI 61 — safe for drinking-water contact.',
  ul_1951_listed: 'UL listing for electric plumbing accessories.',
  ista_1a_certified: 'Packaging transit-test certification (non-simulation).',
  ista_3a_6a_certified: 'Packaging transit-test certification for parcel delivery.',
  ista_certified: 'ISTA packaging transit-test certification.',
  calgreen_compliant: 'California Green Building Standards Code (water-efficient fixtures).',
  title_20_compliant: 'California appliance efficiency regulation — maximum flow limits.',
  title_24_compliant: 'California building energy/water efficiency standard.',
  uplr_compliant: 'Uniform Packaging and Labeling Regulation.',
  ab_100_compliant: 'California low-lead law for plumbing fixtures.',
  sdwa_compliant: 'Safe Drinking Water Act — low-lead requirements.',
  usda_compliant: 'Meets USDA requirements for food-contact materials.',
  taa_compliant: 'Trade Agreements Act — eligible for US government purchasing.',
  scc_compliant: 'Standards Council of Canada compliance.',
  vermont_act_193_compliant: 'Vermont low-lead plumbing law.',
  epa_watersense_certified: 'EPA WaterSense label — at least 20% more water-efficient than standard.',
  energy_efficiency_compliant: 'Meets applicable energy/water efficiency regulations.',
  greenguard_certified: 'GREENGUARD low chemical emissions certification.',
  greenguard_gold_certified: 'GREENGUARD Gold — stricter emissions limits (schools, healthcare).',
  greenguard_certifications: 'GREENGUARD certification details.',
  cradle_to_cradle_certified: 'Cradle to Cradle sustainable-product certification.',
  cradle_to_cradle_certifications: 'Cradle to Cradle certification details.',
  cradle_to_cradle_material_health: 'Cradle to Cradle Material Health certificate level.',
  iso_14021_certified: 'ISO 14021 — self-declared recycled-content claim.',
  pefc_certified: 'PEFC sustainable forestry certification (wood products).',
  sfi_certifications: 'Sustainable Forestry Initiative certification.',
  fsc_certifications: 'Forest Stewardship Council certification (wood products).',
  epd_type_iii: 'Type III Environmental Product Declaration published.',
  safety_listings: 'Safety listings/certifications held (UL, ETL…).',
  safety_listing_registration_number: 'Registration number of the safety listing.',
  canada_product_restriction: 'Whether the product has sales restrictions in Canada.',
  reason_for_restriction: 'Why the product is restricted, if it is.',

  // ---------- Pricing ----------
  msrp_cad: 'Canadian list price. NOT the SinksDirect selling price — the store sells at MAP.',
  map_cad: 'Canadian Minimum Advertised Price — the floor for ads AND the SinksDirect selling price.',
  cost_cad_rona_hd: 'Canadian dealer cost for Rona and Home Depot.',
  cost_cad_wayfair_sod: 'Canadian dealer cost for Wayfair and Small Online Dealers.',
  msrp_usd: 'US list price from the official price list.',
  map_usd: 'US Minimum Advertised Price — no channel may advertise below it.',
  cost_usd_lowes_sod_bbb: 'US dealer cost for Lowes, Small Online Dealers and BB&B.',
  cost_usd_wayfair: 'US dealer cost for Wayfair.',
  cost_usd_menards: 'US dealer cost for Menards.',
  sale_price_cad: 'Discounted price shown while "On sale" is enabled (promotions set this).',
  on_sale: 'Shows the sale price on the store — usually driven by the monthly promotion.',

  // ---------- Visibility / workflow / dates ----------
  visible_online: 'Whether the product is published on the SinksDirect online store. CAUTION: a full Wix push applies this.',
  visible_pos: 'Whether the product shows in Wix Point of Sale (local only, not pushed).',
  pre_order: 'Marks the product as available for pre-order (local only).',
  ribbon: 'Small label shown over the product card on Wix (e.g. "New Arrival").',
  launch_lead: 'Date the launch process starts for this product.',
  sample_available_date: 'When a physical sample is available.',
  ready_to_sell_date: 'When the product is ready to be sold across channels.',
  spec_sheet_needs_update: 'Flags that the spec sheet PDF is outdated.',
  installation_sheet_needs_update: 'Flags that the installation guide PDF is outdated.',
};
